apiVersion: v1
kind: Service
metadata:
  name: metadata
  namespace: default
  labels:
    app: metadata
spec:
  selector:
    app: metadata
  type: NodePort
  ports:
    - port: 80
      targetPort: 6600
